# Default values for odl.
# This is a YAML-formatted file.
# Declare name/values to be passed into your templates.
# name: value


images:
  tags:
    odl_controller: docker.io/sapan2211/odl-karaf-boron:full
  pull_policy: "IfNotPresent"

network:
  node_port:
    dashboard: 8181
  cluster_ip:
    manager: 6640
    controller1: 6653
    controller2: 6633
    odl_neutron_rest: 8080
  port:
    manager: 6640
    controller1: 6653
    controller2: 6633
    odl_neutron_rest: 8080
    dashboard: 8181

labels:
  controller:
    node_selector_key: openstack-control-plane
    node_selector_value: enabled

pod:
  user:
    odl:
      uid: 0
  affinity:
      anti:
        type:
          default: preferredDuringSchedulingIgnoredDuringExecution
        topologyKey:
          default: kubernetes.io/hostname
  replicas:
    controller: 1
  mounts:
    odl_controller:
      odl_controller:
      init_container: null
  lifecycle:
    upgrades:
      deployments:
        revision_history: 3
        pod_replacement_strategy: RollingUpdate
        rolling_update:
          max_unavailable: 1
          max_surge: 3
        odl:
          enabled: false
          min_ready_seconds: 0
          max_unavailable: 1
  resources:
    enabled: true
    controller:
      requests:
        memory: "2048Mi"
        cpu: "1000m"
      limits:
        memory: "4096Mi"
        cpu: "2000m"

manifests:
  configmap_bin: true
  configmap_etc: false
  deployment: true
  service:
    ovs: true
    dashboard: true

endpoints:
  odl:
    name: odl
    hosts:
      default: odl-controller
      public: odl
    host_fqdn_override:
      default: null
    path:
      default: null
    scheme:
      default: http
  dashboard:
    name: odl-dashboard
    hosts:
      default: odl-dashboard
      public: odl-ui
    host_fqdn_override:
      default: null
    path:
      default: null
    scheme:
      default: http
