{{- if .Values.manifests.service.ovs }}
{{- $envAll := . }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ tuple "odl" "internal" . | include "helm-toolkit.endpoints.hostname_short_endpoint_lookup" }}
spec:
  ports:
    - name: ovsdb-manager
      port: {{ .Values.network.port.manager }}
      protocol: TCP
      targetPort: {{ .Values.network.cluster_ip.manager }}
    - name: openflow
      port: {{ .Values.network.port.controller1 }}
      protocol: TCP
      targetPort: {{ .Values.network.cluster_ip.controller1 }}
    - name: rest
      port: {{ .Values.network.port.odl_neutron_rest }}
      protocol: TCP
      targetPort: {{ .Values.network.cluster_ip.odl_neutron_rest }}
  selector:
{{ tuple $envAll "odl" "controller" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 4 }}
{{ end }}
